upstream cms_backend {

	hash $cookie_JSESSIONID consistent;

    {{ range nomadService "tomcat-one" }}
         server {{ .Address }}:9090;
    {{ end}}
    {{ range nomadService "tomcat-two" }}
        server {{ .Address }}:9091;
    {{ end}}

	#server localhost:9090;
	#server localhost:9091;
}

upstream site_backend {

    {{ range nomadService "tomcat-one" }}
         server {{ .Address }}:9090;
    {{ end}}
    {{ range nomadService "tomcat-two" }}
        server {{ .Address }}:9091;
    {{ end}}
	#server localhost:9090;
	#server localhost:9091;
}

server {

	listen 80; server_name cms.example.com;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;

	location /site/ {

		proxy_pass http://site_backend/site/;
	}

	location /cms/ {

		proxy_pass http://cms_backend/cms/;
		#proxy_redirect /cms/ /;
		#proxy_cookie_path /cms /;
	}


}

server {

	listen 80; server_name www.example.com;

      proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;

	location / {

		proxy_pass http://site_backend/site/;
		proxy_redirect /site/ /;
		proxy_cookie_path /site /;
	}


}